### ISSUE TITLE
TODO list for 06/23/18 workshop

### ISSUE THREAD

**Issue by HAIL9000** [djangogirlspdx/docs#6]
- [x] T-shirts (@rachelleahklein & @HAIL9000)
- [x] Pens/notebooks (@rachelleahklein )
- [x] Tote bags (@HAIL9000)
- [x] Catering (lunch/dinner) (@rachelleahklein)
- [x] Breakfast pastries - Back to Eden (@HAIL9000)
- [x] Coffee - Coava on 26th (@HAIL9000)
- [x] Pronoun stickers (@rachelleahklein )
- [ ] Laptops (@rachelleahklein & @HAIL9000)
- [ ] Childcare/stipends (@rachelleahklein)
- [ ] Drinks (@HAIL9000)
- [x] Snacks (@rachelleahklein)
- [ ] Thank you cards (@HAIL9000)
- [ ] Coach floppies (@HAIL9000)
- [x] Decorations and The Box™ (@HAIL9000)
